### ISSUE TITLE
docker-compose.yaml

### ISSUE THREAD

**Issue by evabronskayaa** [Reholly/de-csu#1]
У образов всегда лучше указывать конкретные версии, потому что в один момент latest станет другой функционал, который может быть не совместим с кодом
```yaml
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
```
